### PR TITLE
Hide some rules + some tidying

### PR DESCRIPTION
**Pull request by jchros**
To make the parser lighter as discussed in #5.

The "cleaning up" part is yet to be done.

### CODE REVIEW

**Comment by jchros** [comment]
Some notes:

* The test is failing (intentionally) due to #7; I figured that I'd rather have the test fail now and rebase the branch with the fix later.
* I used `tree-sitter test --update` to generate the updated test cases (whose accuracy I verified manually).  It reformatted the file in a uniform way, and I made it add the field names in the test cases so that they are covered as well.

**Comment by jkbz64** [comment]
I've done some simplifications in tests so it is easier to test on for now since precedences are messed up and this let's me test directly on this branch which has nicer tree, still did not solve the #7.

**Comment by jkbz64** [comment]
Ok, #7 should be fixed, I think you can rebase on top and finish up your PR safely now.

**Comment by jchros** [comment]
The branch should be ready for merging; I've also added some cleanups that go slightly outside of the scope of the discussion at #5:

* I removed the `condition` rule since the addition of the `logical_expression` rules makes it redundant.
* I added a `body` rule for statements that contain multiple statements inside (`IF`, `DO`, `PROCEDURE`, `FUNCTION`, etc.).

**Pull request merged**
